POST http://localhost:8000/api/user/register HTTP/1.1
Content-Type: application/json

{
  "nome" : "a",
  "email" : "1@gmail.com",
  "username" : "a1",
  "pass" : "12345"
}

POST http://localhost:8000/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email" : "1@gmail.com",
  "username" : "a1",
  "pass" : "12345"
}
