POST https://livequest.herokuapp.com/api/user/register HTTP/1.1
Content-Type: application/json

{
  "nome" : "a",
  "email" : "pippo1@gmail.com",
  "pass" : "pippo",
  "username" : "pippo11"
}

###

POST http://localhost:8000/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email" : "pippo1@gmail.com",
  "pass" : "pippo"
}

###

GET http://localhost:8000/api/user/me HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJwaXBwbzFAZ21haWwuY29tIiwiaWF0IjoxNTk4MDI5NDI0LCJleHAiOjE1OTgwMzEyMjQsImlzcyI6ImEifQ.uWlehBdPMEg0IA4WQZE3mBDoENboHoCJwh2_j8grsPg


###
PUT http://localhost:8000/api/user/me HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNTk3MjY0MTc2LCJleHAiOjE1OTcyNjU5NzYsImlzcyI6ImEifQ.0o33sN9N_5t2EJbi1HHqCLB9p-wWpzi0KjD8_8m_4ME
Content-Type: application/json

{
  "nome": "pollo modificato",
  "username": "il mio username",
  "email": "nuovamail@gmail.com"
}

###
GET http://localhost:80/api/user/all HTTP/1.1

###
GET http://localhost:8000/api/user/logout HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNTk4MDI4NzM3LCJleHAiOjE1OTgwMzA1MzcsImlzcyI6ImEifQ.3e3XnHDcSgEn9AZE9uOkkRAXTHXglknOJB8HX0nNeAs

###
DELETE http://localhost:8000/api/user/me HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJwaXBwbzFAZ21haWwuY29tIiwiaWF0IjoxNTk4MDI5MzQzLCJleHAiOjE1OTgwMzExNDMsImlzcyI6ImEifQ.52LUmD-s4xrzDnS5sz2lzCb-QYh2XgmB-tF8zrTLVWk
